name: Publish

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Build
      run: make
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: bin/

  github-release:
    runs-on: ubuntu-latest

    needs:
    - build

    permissions:
      contents: write

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: bin/
    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      continue-on-error: true
      run: >-
        gh release create
        "$(date +'%Y-%m-%d')"
        --repo '${{ github.repository }}'
        --notes ""
    - name: Upload artifact signatures to GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      # Upload to GitHub Release using the `gh` CLI.
      # `dist/` contains the built packages, and the
      # sigstore-produced signatures and certificates.
      run: >-
        gh release upload
        "$(date +'%Y-%m-%d')" bin/**
        --repo '${{ github.repository }}'
